-- ============================================================
-- DEUSTOSPORT — Schema completo
-- Las tablas se crean aquí. Los datos iniciales los gestiona
-- DataInitializer.java (solo en el primer arranque).
-- Para resetear: borra deustosport_app.mv.db y reinicia.
-- ============================================================

CREATE TABLE IF NOT EXISTS usuarios (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(120) NOT NULL,
    email           VARCHAR(150) NOT NULL UNIQUE,
    dni             VARCHAR(20)  UNIQUE,
    telefono        VARCHAR(20),
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    es_socio        BOOLEAN NOT NULL DEFAULT FALSE,
    rol             VARCHAR(20)  NOT NULL
);

CREATE TABLE IF NOT EXISTS instalaciones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(120) NOT NULL,
    direccion    VARCHAR(200) NOT NULL,
    hora_apertura TIME NOT NULL,
    hora_cierre   TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS bonos (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             VARCHAR(80)      NOT NULL,
    creditos_incluidos INTEGER          NOT NULL,
    precio             NUMERIC(10,2)    NOT NULL,
    validez_dias       INTEGER          NOT NULL,
    activo             BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS credenciales (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id               BIGINT       NOT NULL UNIQUE,
    password_hash            VARCHAR(255) NOT NULL,
    token_recuperacion       VARCHAR(255),
    fecha_expiracion_token   TIMESTAMP,
    activo                   BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion           TIMESTAMP    NOT NULL,
    ultimo_acceso            TIMESTAMP,
    CONSTRAINT fk_cred_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS pistas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(60)  NOT NULL,
    tipo_deporte   VARCHAR(20)  NOT NULL,
    instalacion_id BIGINT       NOT NULL,
    max_jugadores  INTEGER      NOT NULL,
    activa         BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_pista_inst FOREIGN KEY (instalacion_id) REFERENCES instalaciones(id)
);

CREATE TABLE IF NOT EXISTS bonos_usuario (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         BIGINT       NOT NULL,
    bono_id            BIGINT       NOT NULL,
    creditos_restantes INTEGER      NOT NULL,
    fecha_compra       DATE         NOT NULL,
    fecha_expiracion   DATE         NOT NULL,
    activo             BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_bu_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_bu_bono    FOREIGN KEY (bono_id)    REFERENCES bonos(id)
);

CREATE TABLE IF NOT EXISTS tarifas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_deporte    VARCHAR(20)   NOT NULL,
    dia_semana      INTEGER       NOT NULL,
    hora_inicio     TIME          NOT NULL,
    hora_fin        TIME          NOT NULL,
    precio_por_hora NUMERIC(10,2) NOT NULL,
    vigente_desde   DATE          NOT NULL,
    vigente_hasta   DATE,
    activa          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS horarios_pista (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pista_id    BIGINT   NOT NULL,
    dia_semana  INTEGER  NOT NULL,
    hora_inicio TIME     NOT NULL,
    hora_fin    TIME     NOT NULL,
    disponible  BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_hp_pista FOREIGN KEY (pista_id) REFERENCES pistas(id)
);

CREATE TABLE IF NOT EXISTS reservas (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pista_id         BIGINT        NOT NULL,
    usuario_id       BIGINT        NOT NULL,
    fecha_reserva    DATE          NOT NULL,
    hora_inicio      TIME          NOT NULL,
    hora_fin         TIME          NOT NULL,
    estado           VARCHAR(20)   NOT NULL DEFAULT 'PENDIENTE',
    precio_total     NUMERIC(10,2) NOT NULL,
    creditos_usados  INTEGER       NOT NULL DEFAULT 0,
    bono_usuario_id  BIGINT,
    metodo_pago      VARCHAR(20),
    referencia_pago  VARCHAR(64),
    fecha_pago       TIMESTAMP,
    CONSTRAINT fk_res_pista   FOREIGN KEY (pista_id)        REFERENCES pistas(id),
    CONSTRAINT fk_res_usuario FOREIGN KEY (usuario_id)      REFERENCES usuarios(id),
    CONSTRAINT fk_res_bono    FOREIGN KEY (bono_usuario_id) REFERENCES bonos_usuario(id)
);

CREATE TABLE IF NOT EXISTS pagos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id      BIGINT        NOT NULL UNIQUE,
    iban            VARCHAR(34)   NOT NULL,
    metodo_pago     VARCHAR(20)   NOT NULL,
    estado_pago     VARCHAR(20)   NOT NULL,
    importe         NUMERIC(10,2) NOT NULL,
    fecha_pago      TIMESTAMP     NOT NULL,
    referencia_pago VARCHAR(100),
    CONSTRAINT fk_pago_reserva FOREIGN KEY (reserva_id) REFERENCES reservas(id)
);

CREATE TABLE IF NOT EXISTS partidas_abiertas (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id            BIGINT       NOT NULL UNIQUE,
    creada_por_usuario_id BIGINT       NOT NULL,
    titulo                VARCHAR(80)  NOT NULL,
    max_jugadores         INTEGER      NOT NULL,
    jugadores_actuales    INTEGER      NOT NULL DEFAULT 1,
    estado                VARCHAR(20)  NOT NULL DEFAULT 'ABIERTA',
    fecha_limite_union    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_pa_reserva FOREIGN KEY (reserva_id)            REFERENCES reservas(id),
    CONSTRAINT fk_pa_usuario FOREIGN KEY (creada_por_usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS participantes_partida_abierta (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partida_abierta_id BIGINT      NOT NULL,
    usuario_id        BIGINT       NOT NULL,
    estado            VARCHAR(20)  NOT NULL DEFAULT 'UNIDO',
    fecha_union       TIMESTAMP    NOT NULL,
    CONSTRAINT uk_partida_usuario    UNIQUE (partida_abierta_id, usuario_id),
    CONSTRAINT fk_ppa_partida        FOREIGN KEY (partida_abierta_id) REFERENCES partidas_abiertas(id),
    CONSTRAINT fk_ppa_usuario        FOREIGN KEY (usuario_id)         REFERENCES usuarios(id)
);

-- ============================================================
-- Índices
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_bono_usuario_usuario   ON bonos_usuario(usuario_id);
CREATE INDEX IF NOT EXISTS idx_horario_pista_dia      ON horarios_pista(pista_id, dia_semana);
CREATE INDEX IF NOT EXISTS idx_pista_tipo_deporte     ON pistas(tipo_deporte);
CREATE INDEX IF NOT EXISTS idx_pista_instalacion      ON pistas(instalacion_id);
CREATE INDEX IF NOT EXISTS idx_reserva_pista_fecha    ON reservas(pista_id, fecha_reserva, hora_inicio);
CREATE INDEX IF NOT EXISTS idx_reserva_usuario        ON reservas(usuario_id);
CREATE INDEX IF NOT EXISTS idx_tarifa_deporte_dia     ON tarifas(tipo_deporte, dia_semana);
CREATE INDEX IF NOT EXISTS idx_tarifa_vigencia        ON tarifas(vigente_desde, vigente_hasta);