plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.3'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
}

group = 'com.deustosport'
version = '0.0.1-SNAPSHOT'
description = 'DeustoSport'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	mockitoAgent
}

repositories {
	mavenCentral()
	maven { url 'https://jitpack.io' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-mail'

	// QR Code generation
	implementation 'com.github.kenglxn.QRGen:javase:3.0.1'

	// JavaMail API
	implementation 'javax.mail:javax.mail-api:1.6.2'
	implementation 'com.sun.mail:javax.mail:1.6.2'

	//
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.0'

	// bd
	runtimeOnly 'org.postgresql:postgresql'
	runtimeOnly 'com.h2database:h2'

	// lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// test
	testRuntimeOnly 'com.h2database:h2'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	mockitoAgent('org.mockito:mockito-core') {
		transitive = false
	}

	// JUnit 4 + ContiPerf (tests de rendimiento)
	testImplementation 'junit:junit:4.13.2'
	testImplementation 'org.databene:contiperf:2.3.4'
	testRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
}

jacoco {
	toolVersion = "0.8.11"
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required = true
		html.required = true
	}
	classDirectories.setFrom(
		files(sourceSets.main.output.classesDirs).asFileTree.matching {
			exclude(
				'**/entity/**',
				'**/dto/**',
				'**/enums/**',
				'**/config/**',
				'**/repository/**',
				'**/*Application*.class'
			)
		}
	)
}

tasks.named('test') {
	useJUnitPlatform()
	jvmArgs "-javaagent:${configurations.mockitoAgent.singleFile.absolutePath}"
	finalizedBy jacocoTestReport
}

tasks.withType(JavaCompile).configureEach {
	options.compilerArgs += '-parameters'
}

springBoot {
	mainClass = 'com.deustosport.my_app.MyAppApplication'
}